# Generated by Django 5.2.8 on 2025-11-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensores',
            name='timestamp',
        ),
    ]
