# Generated by Django 5.2.8 on 2025-11-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_sensores_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambientes',
            name='descricao',
            field=models.TextField(max_length=100),
        ),
    ]
