# Generated by Django 5.2.8 on 2025-11-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ambientes_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsaveis',
            old_name='nome_reponsavel',
            new_name='nome_responsavel',
        ),
    ]
