# Generated by Django 5.2.8 on 2025-11-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_nome_reponsavel_responsaveis_nome_responsavel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambientes',
            old_name='nome_responsavel',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='responsaveis',
            old_name='nome_responsavel',
            new_name='nome',
        ),
    ]
