# Generated by Django 5.2.8 on 2025-11-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_nome_responsavel_ambientes_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensores',
            old_name='mac_adress',
            new_name='mac_address',
        ),
        migrations.RenameField(
            model_name='sensores',
            old_name='unidade_med',
            new_name='unidade_medida',
        ),
    ]
