# Generated by Django 5.2.8 on 2025-12-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_mac_adress_sensores_mac_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico',
            name='ambiente',
        ),
        migrations.AlterField(
            model_name='historico',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='mac_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='sensor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='unidade_medida',
            field=models.CharField(max_length=50),
        ),
    ]
